<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Blog;
use AppBundle\Entity\Comment;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Query;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }

    public function getAllBlogs()
    {

        $em = $this->getEntityManager();
        $blogs = $em->createQueryBuilder()->select('b')->from(Blog::class, 'b')
            ->orderBy('b.id', 'DESC')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        return $blogs;
    }

    public function deleteBlog($blog_id) {

        $em = $this->getEntityManager();
        $blog = $em->getRepository(Blog::class)->find($blog_id);

        if(isset($blog)) {
            $em->remove($blog);
            $em->flush();
        }
    }

}
